---
ID: f13802db-532b-504c-b466-f83a1fa0ef0f
Parent: a0ef7f7f-f7bf-59e4-9c45-6d08886cec5a
Template: 4d50cdae-c2d9-4de8-b080-8f992bfb1b55
Path: /sitecore/content/LibertyMutual/liberty-mutual-agent-portal/Presentation/Headless Variants/ResourceSearch/Default
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: 25bed78c-4957-4165-998a-ca1b52f67497
      Hint: __Created
      Value: 20260910T140000Z
