---
ID: "084b95db-6a27-44b8-bdbc-08f7cfcc3786"
Parent: "ebed7fed-5598-44d4-ba9e-8a4729cc0130"
Template: "ebed7fed-5598-44d4-ba9e-8a4729cc0130"
Path: /sitecore/templates/Project/LibertyMutual/JSS Settings/__Standard Values
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20260910T134153Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\thomas.lin@sitecore.com
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\thomas.lin@sitecore.com
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "c027d36f-5ffb-4371-89b8-c9eb0270cbd5"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\thomas.lin@sitecore.com
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20260910T134153Z
