---
ID: "c2d26f86-2905-47bf-ad16-825211c17fff"
Parent: "2ec94e3d-439c-4fc6-bd4e-f08c7ddd9203"
Template: "2ec94e3d-439c-4fc6-bd4e-f08c7ddd9203"
Path: /sitecore/templates/Project/LibertyMutual/Page/__Standard Values
SharedFields:
- ID: "1172f251-dad4-4efb-a329-0c63500e4f1e"
  Hint: __Masters
  Value: |
    {2EC94E3D-439C-4FC6-BD4E-F08C7DDD9203}
    {C14B6289-8AC2-439C-9E5B-40DE9F820C3F}
- ID: "dbbbeca1-21c7-4906-9dd2-493c1efa59a2"
  Hint: __Shared revision
  Value: "5877a8ca-d5c7-473e-8cef-186a8cad17ca"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20260910T134151Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\thomas.lin@sitecore.com
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\thomas.lin@sitecore.com
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "939dc70c-f939-41ff-b9dd-aa748dab48c9"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\thomas.lin@sitecore.com
    - ID: "d3bed2bd-a5f0-49ab-b7a5-6b72b0f34e4b"
      Hint: Title
      Value: $name
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20260910T134157Z
